### PR TITLE
Fix labels with plural units

### LINKED ISSUE #3: It doesn't seem to work at all

### PR DESCRIPTION
**Pull request by coadler**
also adds tests

### CODE REVIEW

**Comment by coadler** [comment]
@kylecarbs @scsmithr pls review

**Comment by coadler** [comment]
@nathanpotter pls review

**Comment by kylecarbs** [comment]
merged before we could review—sus

**Comment by coadler** [comment]
wouldn’t let me tag non repo members and i got impatient :(

**Pull request merged**
